name: gamingowls
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.5+17

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  blurhash: 0.2.0
  cached_network_image: ^2.2.0+1
  cloud_firestore: ^0.16.0
  cloud_functions: ^0.9.0
  connectivity: ^0.4.9+2
  crop: ^0.4.0
  cupertino_icons: ^0.1.3
  firebase_remote_config: ^0.6.0
  # firebase_admob: ^0.11.0+1
  firebase_analytics: ^7.0.1
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  firebase_crashlytics: ^0.4.0+1
  firebase_messaging: ^8.0.0-dev.14
  firebase_storage: ^7.0.0
  flutter_blurhash: ^0.5.0
  flutter_facebook_auth: ^2.0.0+1
  flutter_icons: ^1.1.0
  flutter_native_admob: ^2.1.0+3
  flutter_signin_button: ^1.0.0
  flutter_svg: ^0.19.3
  fluttertoast: ^7.0.1+1
  form_field_validator: ^1.0.1
  get: ^3.22.2
  get_it: ^4.0.4
  google_sign_in: ^4.5.1
  http: ^0.12.2
  image_picker: ^0.6.7+4
  package_info: ^0.4.3+2
  path: ^1.7.0
  path_provider: ^1.6.11
  provider: ^4.3.1
  shared_preferences: ^0.5.8
  shimmer: ^1.1.1
  url_launcher: ^5.5.0
  uuid: 2.2.0
  webview_flutter: ^1.0.7
  
# dependency_overrides:
#   intl: 0.16.1
  # xml : 4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"
  flutter_native_splash: ^0.1.9
  # image: ^2.1.14




flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logoCircleSmall.png"
  # effective_dart: ^1.2.0

flutter_native_splash:
  image: assets/logoCircle.png
  color: "000000"
  fill: true

flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: Righteous
      fonts:
        - asset: fonts/Righteous.ttf
